Add Basic UI
Kidd254/OOP_school_library pull request #4
Opened 2023-08-30 15:25 UTC by Kidd254

In this pull request I:
**- [ ] Created a app.rb file that will serve as my console app entry-point with the following methods:**
1.     List all books.
2.     List all people.
3.     Create a person (teacher or student, not a plain Person).
4.     Create a book.
5.     Create a rental.
6.     List all rentals for a given person id.

**- [ ] Add an entry point main.rb which is meant to do the following:**
1. Present the user with a list of options to perform.
2. Lets users choose an option.
3. If needed, ask for parameters for the option.
4. Have a way to quit the app.

2023-08-30 15:37 UTC, BregornOriginal requested changes
Hi @Kidd254  

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![giphy (5)](https://github.com/Kidd254/OOP_school_library/assets/93630700/20d87a81-79b9-4818-97f6-461dcca66f8a)

## Highlights

✅ Linters are passing
✅ Good commit history
✅ Good work implementing the UI for this app! 🥇 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-30 15:37 UTC, BregornOriginal commented on main.rb
> +    p app.instance_variable_get(:@people) # Print people array
- [ ] Kindly, while listing books and persons, fix the issue where the instance is being printed on the screen, This makes your UI look bad and it's not necessary for the final user
- [ ] Also, after creating a person. I get the `unknown` response from `list all people`, kindly fix this bug

![image](https://github.com/Kidd254/OOP_school_library/assets/93630700/12a098c3-b67b-4f57-b403-0f39faa9d685)

2023-08-30 19:21 UTC, Owusu-Desmond requested changes
Hi @Kidd254 , :wave: 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some changes you still need to work on before you move on to the next project but you are almost there.

<img src="https://media1.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif"/>

 ## Highlights :+1: 
:heavy_check_mark: Good commit history.
:heavy_check_mark: No linter errors.
:heavy_check_mark: Your project is well documented


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-30 19:21 UTC, Owusu-Desmond commented on student.rb
>    end
- [ ] From the project requirement, you should make sure your student's school library console app behaves in the same way as the [example video](https://www.youtube.com/watch?v=vkkgrhD6aXQ) but currently I am getting an error saying that you are passing a wrong number of arguments to the `Student` class at line 20 in this `student.rb` file so I suggest you pass the expected number of arguments to fix this issue and ensure your app is working fine as the [example video](https://www.youtube.com/watch?v=vkkgrhD6aXQ). See the issue in the screenshot below :point_down: 

![image](https://github.com/Kidd254/OOP_school_library/assets/92303891/70c6fed4-e178-45c8-acbe-99d731e8d385)

2023-08-31 17:08 UTC, mikethreels requested changes
Hi Lawrence, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
- good job creating the UI.

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-31 17:08 UTC, mikethreels commented on app.rb
> +      person = Student.new(age, name, parent_permission: parent_permission)
- [ ] good job however, right now when a user wants to add a student the name is unknown because that's the default value you gave to it. because the student class is expecting a classroom before the student's name and this isn't given. one option you can do to fix this is to pass a value for the classroom when calling the student class.

2023-08-31 20:45 UTC, FrederickMih requested changes
## Hi :raising_hand: :raising_hand: @Kidd254 , 


Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


<img src="https://media.giphy.com/media/r5eafWP6dcbxX8cLeN/giphy.gif"  width ="150"><img>

## Highlights :green_circle: 

- Some previous issues have been addressed :+1: 


## Required Changes ♻️
**N/A**
_Check the comments under the review._

## Optional suggestions
**N/A**

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-31 20:45 UTC, FrederickMih commented on main.rb
> +    app.create_book
- [ ] Hi @Kidd254, great job taking your time to address some issues raised by the previous reviewers, however, some issues are not yet addressed. Your app is not really responding as the one in the provided  video as pointed out by the previous reviewer. I needs to input an option twice before it get executed as you'll see in the record below. Some information is being display at the top of options which are not found in the provided video. Again as pointed out by the previous reviewers, when creating an instance of a Person, an object is being display at the bottom causing the interface to look unpleasant. Kindly also check the record below and address these issues.


[Screencast from 08-31-2023 09:21:35 PM.webm](https://github.com/Kidd254/OOP_school_library/assets/63087491/14245911-997e-4376-b67c-1abc40c7b59d)

2023-08-31 21:38 UTC, MahmoudBakr23 requested changes
Hi @Kidd254 😃, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but some have still not been addressed yet.

> I'd like to remind you that your long hours of work are appreciated. However, the code review process is for improving the code you wrote, and not for criticizing it. 😄

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were missed by the previous reviewer and addressing them will really improve your application._

N/A

Cheers, and Happy coding!👏👨‍💻💻

Feel free to mention @MahmoudBakr23 to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-31 21:38 UTC, MahmoudBakr23 commented on main.rb
>      person_id = gets.chomp.to_i
- [ ] Well done working on the requested changes so far. However, please inspect the below error message that prevents the app from running accordingly. 🙏
![MINGW64__c_Users_mbakr_OneDrive_Desktop_OOP_school_library 9_1_2023 12_35_09 AM](https://github.com/Kidd254/OOP_school_library/assets/47625407/19caf106-846e-4886-989d-f762436793da)

It only shows the list of options after clicking `ctrl + c` to cut off the crashed execution.

2023-08-31 22:19 UTC, Kidd254 commented on main.rb
>      person_id = gets.chomp.to_i
Hello @MahmoudBakr23  Ithink the code works perfectly because i have also tested it using git bash and this was the results 
![image](https://github.com/Kidd254/OOP_school_library/assets/106907574/95700f06-6e32-4395-9679-7b47cbe1c604)

2023-08-31 22:20 UTC, Kidd254 commented on main.rb
>      person_id = gets.chomp.to_i
@MahmoudBakr23 you are using _ruby ./main.rb_ instead of **ruby main.rb**

2023-08-31 22:38 UTC, fobadara approved these changes
Hi @Kidd254, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![APPRVED](https://user-images.githubusercontent.com/62938735/260206857-3c93f52c-5b21-4f6f-8bc4-be158a13d3cd.gif)
## Highlights
✅ Descriptive README
✅ Descriptive PR summary
✅ Clean code


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-01 07:20 UTC, merged